# Generated by Django 3.0.8 on 2020-07-28 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0005_auto_20200727_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(related_name='project_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
