# Generated by Django 3.0.8 on 2020-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_projectjoinpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githubrepo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repoowner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
