# Generated by Django 3.0.8 on 2020-07-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='tag',
            new_name='tags',
        ),
    ]
