# Generated by Django 3.0.8 on 2020-07-22 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_issue_solve'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='issues.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('issue', 'user')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='members',
            field=models.ManyToManyField(through='issues.IssueMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
