# Generated by Django 3.0.8 on 2020-07-28 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0007_auto_20200728_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(related_name='likes_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
