# Generated by Django 3.0.8 on 2020-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_auto_20200728_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['date_added']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
