# Generated by Django 3.0.8 on 2020-07-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='slug',
        ),
    ]
