# Generated by Django 3.0.8 on 2020-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank-profile-picture.jpg', null=True, upload_to='static/images/'),
        ),
    ]
