# Generated by Django 3.0.8 on 2020-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200730_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank-profile-picture.jpg', null=True, upload_to=''),
        ),
    ]
