# Generated by Django 3.0.8 on 2020-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200811_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://aesusdesign.com/wp-content/uploads/2019/06/mans-blank-profile.png', null=True),
        ),
    ]
