# Generated by Django 3.0.8 on 2020-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200820_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(default='https://aesusdesign.com/wp-content/uploads/2019/06/mans-blank-profile.png'),
        ),
    ]
