# Generated by Django 3.0.8 on 2020-08-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('issues', '0001_initial'),
        ('chats', '0002_auto_20200808_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
