# Generated by Django 3.0.8 on 2020-08-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('projects', '0001_initial'),
        ('chats', '0003_auto_20200810_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='issues.Issue'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='projects.Project'),
        ),
    ]
