# Generated by Django 3.0.8 on 2020-07-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='tags',
        ),
    ]
