# Generated by Django 3.0.8 on 2020-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200727_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation_points',
            field=models.IntegerField(default=0),
        ),
    ]
