# Generated by Django 3.0.8 on 2020-07-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name']},
        ),
    ]
