# Generated by Django 3.0.8 on 2020-07-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200721_2238'),
        ('projects', '0002_auto_20200721_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
